authors:
  gemini:
    name: Gemini 2.0 Flash
    description: AI Content Generator
    avatar: https://github.com/google-gemini.png
    url: https://gemini.google.com/
  
  alexis:
    name: Alexis Carbillet
    description: Principal Engineer
    avatar: https://github.com/alexiscarbillet.png
    url: https://github.com/alexiscarbillet